"""Prompt bundle: system prompt + output contract, extracted mechanically from the prompt README.

The .txt files are generated by `python -m src.prompts.sync` and checked against the README by tests,
so they cannot drift. Every provider receives the same text.
"""
from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
README = ROOT / "SMS_AI_SURVEILLANCE_PROMPT_README.md"
SYSTEM_FILE = Path(__file__).with_name("system_prompt.txt")
CONTRACT_FILE = Path(__file__).with_name("output_contract.txt")


def extract_from_readme(text: str) -> tuple[str, str, str]:
    """Return (system_prompt, output_contract, prompt_version)."""
    m = re.search(r"## Baseline system prompt v[\d.]+\n+```text\n(.*?)\n```", text, re.S)
    if not m:
        raise ValueError("system prompt block not found in README")
    start = text.index("## Required JSON output shape")
    end = text.index("## Multi-turn input")
    contract = text[start:end].rstrip().removesuffix("---").rstrip()
    version = re.search(r"prompt_version = (v[\d.]+)", text).group(1)
    return m.group(1), contract, version


def sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class PromptBundle:
    version: str
    system_prompt: str
    output_contract: str

    @property
    def system_text(self) -> str:
        return f"{self.system_prompt}\n\nOUTPUT CONTRACT\n\n{self.output_contract}\n"

    def hashes(self) -> dict:
        return {"system_prompt": sha256(self.system_prompt), "output_contract": sha256(self.output_contract),
                "system_text": sha256(self.system_text)}


def load_bundle() -> PromptBundle:
    return PromptBundle(
        version=re.search(r"prompt_version = (v[\d.]+)", README.read_text(encoding="utf-8")).group(1),
        system_prompt=SYSTEM_FILE.read_text(encoding="utf-8").rstrip("\n"),
        output_contract=CONTRACT_FILE.read_text(encoding="utf-8").rstrip("\n"),
    )
